name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "fr_FR/**/*.md"
      - ".github/workflows/ci.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          config: '.markdownlint.json'
          globs: "fr_FR/**/*.md"
