name: Docs translate

on:
  workflow_dispatch:
    inputs:
      target_languages:
        description: "Comma-separated target languages"
        required: false
        default: "de_DE,es_ES,en_US"

permissions:
  contents: write
  pull-requests: write

jobs:
  translate-arlo:
    runs-on: ubuntu-latest
    steps:
      - uses: Mips2648/docs-translations@main
        with:
            deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
            target_languages: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target_languages || 'en_US,es_ES,de_DE' }}
            documents_roots: 'arlo,portainer'